# Site settings
title: Heejin
description: "Jekyll-Uno - a minimal, responsive theme for Jekyll"
url: "http://joshgerdes.com/jekyll-uno"
baseurl: ""
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
disable_landing_page: true

author:
  name: "Josh Gerdes"
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username: heejinee3
  linkedin_username: joshgerdes

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 10
permalink: /project/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ["jekyll-paginate"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
