# Site settings
title: Heejin
description: "Portfolio & Blog"
url: "http://joshgerdes.com/jekyll-uno"
baseurl: ""
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
disable_landing_page: true

author:
  name: "Jeong Heejin"
  email: naahah79@naver.com
  youtube_username:
  velog_username: chunjakim
  github_username: Heejinee3
  instagram_username:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ["jekyll-paginate", "jekyll-admin"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
