# projects section data
- name: Analysis-of-YouTube-Trending-Videos
  title: Analysis of YouTube Trending Videos
  repo: https://github.com/Heejinee3/Analysis-of-YouTube-Trending-Videos
  code: https://github.com/Heejinee3/Analysis-of-YouTube-Trending-Videos/tree/master/Code
  docs: https://github.com/Heejinee3/Analysis-of-YouTube-Trending-Videos/tree/master/Docs
  img: /assets/project/Analysis-of-YouTube-Trending-Videos/MainFigure.PNG
  desc: "This is the project in which we analyzed YouTube Trending Videos using R to determine which variables had a significant impact on the number of views and identify the most effective approach to increase view counts."
  start_date: Sep 2020
  end_date: Dec 2020
  tags: [R]

- name: Mysoho-Shopping-Mall-Website
  title: 마이소호 쇼핑몰 웹사이트
  repo: https://github.com/Heejinee3/Mysoho-Shopping-Mall-Website
  code: https://github.com/Heejinee3/Mysoho-Shopping-Mall-Website/tree/main/Code
  docs: https://github.com/Heejinee3/Mysoho-Shopping-Mall-Website/tree/main/Docs
  demo: https://www.youtube.com/watch?v=A38tptt7irM
  img: /assets/project/Mysoho-Shopping-Mall-Website/MainFigure.PNG
  desc: "이 프로젝트는 HTML, JavaScript, CSS, 그리고 SpringBoot(Java)을 이용하여 쇼핑몰 웹사이트를 구현한 프로젝트이다. 마이소호 샘플샵 웹사이트을 기반으로 만들어졌으며, 사용자에게 편리한 쇼핑 경험을 제공하기 위해 다양한 기능을 포함하고 있다."
  start_date: Jan 2023
  end_date: Mar 2023
  tags:
    [
      Java,
      JavaScript,
      HTML,
      CSS,
      Kotlin,
      SpringBoot,
      Bootstrap5,
      Git,
      MariaDB,
      AWS RDS,
      Github Actions,
      AWS CodeDeploy,
      AWS S3,
      AWS EC2,
    ]

- name: Ulidongne-App
  title: 우리동네 앱
  repo:
  code:
  docs:
  demo:
  img: /assets/project/Ulidongne-App/MainFigure.png
  desc:
    "'우리동네'는 동일한 동네에 사는 사람들을 위한 안드로이드 어플리케이션이며, 사용자들이 공유하는
    취미와 관심사를 기반으로 다른 사람들과 온라인 및 오프라인에서 일정을 잡을 수 있다.
    사용자들은 앱을 통해 자신의 취미, 관심사를 등록하고, 동일한 동네에 있는 다른 사용자들과
    쉽게 소통하며 일정을 조율할 수 있다."
  start_date: Apr 2023
  end_date: May 2023
  tags:
    [
      Java,
      JavaScript,
      HTML,
      CSS,
      Kotlin,
      SpringBoot,
      Bootstrap5,
      Git,
      MariaDB,
      AWS RDS,
      Github Actions,
      AWS CodeDeploy,
      AWS S3,
      AWS EC2,
    ]
